S -> S'
S' -> COMANDO DOISPONTOVIRGULA CONT
S' -> COMANDO CONT
CONT -> COMANDO DOISPONTOVIRGULA CONT
CONT -> COMANDO CONT
CONT ->
COMANDO -> EXPR
COMANDO -> OPEN ID
EXPR -> EXPR_A
EXPR_A -> EXPR_B
EXPR_A -> DECLARACAO
EXPR_A -> EXPR_A IN EXPR_A
DECLARACAO -> LET ID IGUAL EXPR_B
DECLARACAO -> LET ID DOISPONTO ID IGUAL EXPR_B
DECLARACAO -> LET ID DOISPONTO ID ID IGUAL EXPR_B
DECLARACAO -> LET ID IGUAL EXPR_B
DECLARACAO -> LET ID DOISPONTO ID IGUAL EXPR_B
DECLARACAO -> LET ID DOISPONTO ID ID IGUAL EXPR_B
EXPR_A -> FUNCAO
EXPR_A -> FUNCAO_RETORNO
FUNCAO -> LET ID PARAMS IGUAL EXPR
FUNCAO -> LET ID EPAR DPAR IGUAL EXPR
FUNCAO -> LET REC ID PARAMS IGUAL EXPR
FUNCAO -> LET EPAR DPAR IGUAL EXPR
FUNCAO_RETORNO -> LET ID PARAMS DOISPONTO ID IGUAL EXPR
FUNCAO_RETORNO -> LET ID EPAR DPAR DOISPONTO ID IGUAL EXPR
FUNCAO_RETORNO -> LET REC ID PARAMS DOISPONTO ID IGUAL EXPR
PARAMS -> ID PARAM
PARAMS -> EPAR ID DOISPONTO ID CONT_PARAM
PARAM -> EPAR ID DOISPONTO ID CONT_PARAM
CONT_PARAM -> DPAR PARAM
CONT_PARAM -> ID CONT_PARAM
PARAM -> ID PARAM
PARAM ->
EXPR_B -> EXPR_B1
EXPR_B -> EXPR_B1 PONTOVIRGULA DIR_EXPR_B
DIR_EXPR_B -> EXPR
DIR_EXPR_B ->
EXPR_B1 -> EXPR_C
EXPR_B1 -> WHILE EXPR DO EXPR DONE
EXPR_C -> EXPR_D
EXPR_C -> IF EXPR_D THEN EXPR_D IF_ELSE
IF_ELSE -> ELSE EXPR_D
IF_ELSE -> ELSE IF EXPR_D THEN EXPR_D IF_ELSE
IF_ELSE ->
EXPR_D -> EXPR_E
EXPR_D -> EXPR_E SETAE EXPR_D
EXPR_D -> EXPR_E DOISPONTOIGUAL EXPR_D
EXPR_E -> EXPR_F
EXPR_E -> EXPR_F OR EXPR_E
EXPR_E -> EXPR_F OULOG EXPR_E
EXPR_F -> EXPR_G
EXPR_F -> EXPR_G EBIT EXPR_F
EXPR_F -> EXPR_G ELOG EXPR_F
EXPR_G -> EXPR_H
EXPR_G -> EXPR_G MAIORIGUAL EXPR_H
EXPR_G -> EXPR_G MENORIGUAL EXPR_H
EXPR_G -> EXPR_G IGUALIGUAL EXPR_H
EXPR_G -> EXPR_G IGUAL EXPR_H
EXPR_G -> EXPR_G MENOR EXPR_H
EXPR_G -> EXPR_G MAIOR EXPR_H
EXPR_G -> EXPR_G OUBIT EXPR_H
EXPR_G -> EXPR_G DIFF EXPR_H
EXPR_H -> EXPR_I
EXPR_H -> EXPR_I ARROBA EXPR_H
EXPR_H -> EXPR_I CHAPEU EXPR_H
EXPR_I -> EXPR_J
EXPR_I -> EXPR_I MAIS EXPR_J
EXPR_I -> EXPR_I MENOS EXPR_J
EXPR_I -> EXPR_I MENOSPONTO EXPR_J
EXPR_I -> EXPR_I INFIX_SYMBOL EXPR_J
EXPR_I -> EXPR_I MAISPONTO EXPR_J
EXPR_J -> EXP_K
EXPR_J -> EXPR_J MOD EXP_K
EXPR_J -> EXPR_J BARRAPONTO EXP_K
EXPR_J -> EXPR_J ASTPONTO EXP_K
EXPR_J -> EXPR_J AST EXP_K
EXPR_J -> EXPR_J BARRA EXP_K
EXP_K -> EXPR_L
EXP_K -> EXP_K ASTAST EXPR_L
EXPR_L -> EXPR_M
EXPR_L -> MENOS EXPR_L
EXPR_L -> MENOSPONTO EXPR_L
EXPR_L -> TILMENOS EXPR_L
EXPR_L -> TILMENOSPONTO EXPR_L
EXPR_M -> EXPR_N
EXPR_M -> ID EPAR DPAR
EXPR_M -> ID EXPR_M CALL
CALL -> EXPR_M CALL
CALL ->
EXPR_N -> EXPR_O
EXPR_N -> PREFIX_SYMBOL EXPR_N
EXPR_O -> EXPR_P
EXPR_O -> EPAR EXPR DPAR
EXPR_O -> BEGIN EXPR END
EXPR_P -> ID
EXPR_P -> INT
EXPR_P -> FLOAT
EXPR_P -> CHAR
EXPR_P -> STRING
EXPR_P -> FALSE
EXPR_P -> TRUE
EXPR_P -> UNIT
EXPR_P -> ACESSO_ARRAY
ACESSO_ARRAY -> ID PONTO EPAR INT DPAR
EXPR_P -> ARRAY
ARRAY -> COLOU EXPR ARR
ARR -> PONTOVIRGULA EXPR ARR
ARR -> OUCOL
UNIT -> EPAR DPAR
