/* Generated By:JavaCC: Do not edit this line. OcamlParserConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface OcamlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int INTEIRO = 10;
  /** RegularExpression Id. */
  int NUM_INTEIRO_HEX = 11;
  /** RegularExpression Id. */
  int NUM_INTEIRO_OCTAL = 12;
  /** RegularExpression Id. */
  int NUM_INTEIRO_BINARIO = 13;
  /** RegularExpression Id. */
  int NUM_INTEIRO = 14;
  /** RegularExpression Id. */
  int INTEIRO_32_BIT = 15;
  /** RegularExpression Id. */
  int INTEIRO_64_BIT = 16;
  /** RegularExpression Id. */
  int INTEIRO_NATIVE = 17;
  /** RegularExpression Id. */
  int FLOAT = 18;
  /** RegularExpression Id. */
  int ESCAPE_CHAR = 19;
  /** RegularExpression Id. */
  int CHAR = 20;
  /** RegularExpression Id. */
  int UNICODE_CHAR = 21;
  /** RegularExpression Id. */
  int STRING = 22;
  /** RegularExpression Id. */
  int LABEL = 23;
  /** RegularExpression Id. */
  int OPTLABEL = 24;
  /** RegularExpression Id. */
  int AND = 25;
  /** RegularExpression Id. */
  int AS = 26;
  /** RegularExpression Id. */
  int ASSERT = 27;
  /** RegularExpression Id. */
  int ASR = 28;
  /** RegularExpression Id. */
  int BEGIN = 29;
  /** RegularExpression Id. */
  int CONSTRAINT = 30;
  /** RegularExpression Id. */
  int DO = 31;
  /** RegularExpression Id. */
  int DONE = 32;
  /** RegularExpression Id. */
  int DOWNTO = 33;
  /** RegularExpression Id. */
  int ELSE = 34;
  /** RegularExpression Id. */
  int EXCEPTION = 35;
  /** RegularExpression Id. */
  int EXTERNAL = 36;
  /** RegularExpression Id. */
  int FALSE = 37;
  /** RegularExpression Id. */
  int FOR = 38;
  /** RegularExpression Id. */
  int FUN = 39;
  /** RegularExpression Id. */
  int FUNCTOR = 40;
  /** RegularExpression Id. */
  int IF = 41;
  /** RegularExpression Id. */
  int IN = 42;
  /** RegularExpression Id. */
  int INCLUDE = 43;
  /** RegularExpression Id. */
  int INHERIT = 44;
  /** RegularExpression Id. */
  int LAND = 45;
  /** RegularExpression Id. */
  int LAZY = 46;
  /** RegularExpression Id. */
  int LET = 47;
  /** RegularExpression Id. */
  int LOR = 48;
  /** RegularExpression Id. */
  int LSL = 49;
  /** RegularExpression Id. */
  int LXOR = 50;
  /** RegularExpression Id. */
  int MATCH = 51;
  /** RegularExpression Id. */
  int METHOD = 52;
  /** RegularExpression Id. */
  int MOD = 53;
  /** RegularExpression Id. */
  int MODULE = 54;
  /** RegularExpression Id. */
  int NEW = 55;
  /** RegularExpression Id. */
  int NONREC = 56;
  /** RegularExpression Id. */
  int OBJECT = 57;
  /** RegularExpression Id. */
  int OF = 58;
  /** RegularExpression Id. */
  int OPEN = 59;
  /** RegularExpression Id. */
  int PRIVATE = 60;
  /** RegularExpression Id. */
  int REC = 61;
  /** RegularExpression Id. */
  int SIG = 62;
  /** RegularExpression Id. */
  int STRUCT = 63;
  /** RegularExpression Id. */
  int THEN = 64;
  /** RegularExpression Id. */
  int TRUE = 65;
  /** RegularExpression Id. */
  int TRY = 66;
  /** RegularExpression Id. */
  int TYPE = 67;
  /** RegularExpression Id. */
  int VAL = 68;
  /** RegularExpression Id. */
  int VIRTUAL = 69;
  /** RegularExpression Id. */
  int WHILE = 70;
  /** RegularExpression Id. */
  int WITH = 71;
  /** RegularExpression Id. */
  int CLASS = 72;
  /** RegularExpression Id. */
  int END = 73;
  /** RegularExpression Id. */
  int FUNCTION = 74;
  /** RegularExpression Id. */
  int INITIALIZER = 75;
  /** RegularExpression Id. */
  int LSR = 76;
  /** RegularExpression Id. */
  int MUTABLE = 77;
  /** RegularExpression Id. */
  int OR = 78;
  /** RegularExpression Id. */
  int TO = 79;
  /** RegularExpression Id. */
  int WHEN = 80;
  /** RegularExpression Id. */
  int DIFF = 81;
  /** RegularExpression Id. */
  int HASHTAG = 82;
  /** RegularExpression Id. */
  int EBIT = 83;
  /** RegularExpression Id. */
  int ELOG = 84;
  /** RegularExpression Id. */
  int ASPA = 85;
  /** RegularExpression Id. */
  int EPAR = 86;
  /** RegularExpression Id. */
  int DPAR = 87;
  /** RegularExpression Id. */
  int AST = 88;
  /** RegularExpression Id. */
  int MAIS = 89;
  /** RegularExpression Id. */
  int VIRGULA = 90;
  /** RegularExpression Id. */
  int MENOS_PONTO = 91;
  /** RegularExpression Id. */
  int SETAD = 92;
  /** RegularExpression Id. */
  int PONTO = 93;
  /** RegularExpression Id. */
  int PONTOPONTO = 94;
  /** RegularExpression Id. */
  int PONTOTIL = 95;
  /** RegularExpression Id. */
  int DOISPONTO = 96;
  /** RegularExpression Id. */
  int DOISDOISPONTO = 97;
  /** RegularExpression Id. */
  int DOISPONTOIGUAL = 98;
  /** RegularExpression Id. */
  int DOISPONTOMAIOR = 99;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 100;
  /** RegularExpression Id. */
  int MENOR = 101;
  /** RegularExpression Id. */
  int SETAE = 102;
  /** RegularExpression Id. */
  int IGUAL = 103;
  /** RegularExpression Id. */
  int MAIORCOLD = 104;
  /** RegularExpression Id. */
  int MAIORCH = 105;
  /** RegularExpression Id. */
  int INTER = 106;
  /** RegularExpression Id. */
  int ECOL = 107;
  /** RegularExpression Id. */
  int MENORCOL = 108;
  /** RegularExpression Id. */
  int MAIOR = 109;
  /** RegularExpression Id. */
  int DCOL = 110;
  /** RegularExpression Id. */
  int UNDELINE = 111;
  /** RegularExpression Id. */
  int CRASE = 112;
  /** RegularExpression Id. */
  int ECHAVE = 113;
  /** RegularExpression Id. */
  int ECHAVEMENOR = 114;
  /** RegularExpression Id. */
  int OUBIT = 115;
  /** RegularExpression Id. */
  int OUCOL = 116;
  /** RegularExpression Id. */
  int OULOG = 117;
  /** RegularExpression Id. */
  int DCHAVE = 118;
  /** RegularExpression Id. */
  int TIL = 119;
  /** RegularExpression Id. */
  int MENOS = 120;
  /** RegularExpression Id. */
  int DOISPONTOVIRGULA = 121;
  /** RegularExpression Id. */
  int COLOU = 122;
  /** RegularExpression Id. */
  int MAIORIGUAL = 123;
  /** RegularExpression Id. */
  int MENORIGUAL = 124;
  /** RegularExpression Id. */
  int IGUALIGUAL = 125;
  /** RegularExpression Id. */
  int ASTAST = 126;
  /** RegularExpression Id. */
  int BARRAPONTO = 127;
  /** RegularExpression Id. */
  int ASTPONTO = 128;
  /** RegularExpression Id. */
  int TILMENOSPONTO = 129;
  /** RegularExpression Id. */
  int MAISPONTO = 130;
  /** RegularExpression Id. */
  int BARRA = 131;
  /** RegularExpression Id. */
  int TILMENOS = 132;
  /** RegularExpression Id. */
  int ARROBA = 133;
  /** RegularExpression Id. */
  int CHAPEU = 134;
  /** RegularExpression Id. */
  int LINENUM_DIRECTIVE = 135;
  /** RegularExpression Id. */
  int ID = 136;
  /** RegularExpression Id. */
  int LETRA = 137;
  /** RegularExpression Id. */
  int DIGITO = 138;
  /** RegularExpression Id. */
  int LOWER_ID = 139;
  /** RegularExpression Id. */
  int UPPER_ID = 140;
  /** RegularExpression Id. */
  int CHAR_OPERADOR_CORE = 141;
  /** RegularExpression Id. */
  int CHAR_OPERADOR = 142;
  /** RegularExpression Id. */
  int PREFIX_SYMBOL = 143;
  /** RegularExpression Id. */
  int INFIX_SYMBOL = 144;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(*\"",
    "\"(*\"",
    "\"*)\"",
    "<token of kind 4>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<INT>",
    "<INTEIRO>",
    "<NUM_INTEIRO_HEX>",
    "<NUM_INTEIRO_OCTAL>",
    "<NUM_INTEIRO_BINARIO>",
    "<NUM_INTEIRO>",
    "<INTEIRO_32_BIT>",
    "<INTEIRO_64_BIT>",
    "<INTEIRO_NATIVE>",
    "<FLOAT>",
    "<ESCAPE_CHAR>",
    "<CHAR>",
    "<UNICODE_CHAR>",
    "<STRING>",
    "<LABEL>",
    "<OPTLABEL>",
    "\"and\"",
    "\"as\"",
    "\"assert\"",
    "\"asr\"",
    "\"begin\"",
    "\"constraint\"",
    "\"do\"",
    "\"done\"",
    "\"downto\"",
    "\"else\"",
    "\"exception\"",
    "\"external\"",
    "\"false\"",
    "\"for\"",
    "\"fun\"",
    "\"functor\"",
    "\"if\"",
    "\"in\"",
    "\"include\"",
    "\"inherit\"",
    "\"land\"",
    "\"lazy\"",
    "\"let\"",
    "\"lor\"",
    "\"lsl\"",
    "\"lxor\"",
    "\"match\"",
    "\"method\"",
    "\"mod\"",
    "\"module\"",
    "\"new\"",
    "\"nonrec\"",
    "\"object\"",
    "\"of\"",
    "\"open\"",
    "\"private\"",
    "\"rec\"",
    "\"sig\"",
    "\"struct\"",
    "\"then\"",
    "\"true\"",
    "\"try\"",
    "\"type\"",
    "\"val\"",
    "\"virtual\"",
    "\"while\"",
    "\"with\"",
    "\"class\"",
    "\"end\"",
    "\"function\"",
    "\"initializer\"",
    "\"lsr\"",
    "\"mutable\"",
    "\"or\"",
    "\"to\"",
    "\"when\"",
    "\"!=\"",
    "\"#\"",
    "\"&\"",
    "\"&&\"",
    "\"\\\'\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"+\"",
    "\",\"",
    "\"-.\"",
    "\"->\"",
    "\".\"",
    "\"..\"",
    "\".~\"",
    "\":\"",
    "\"::\"",
    "\":=\"",
    "\":>\"",
    "\";\"",
    "\"<\"",
    "\"<-\"",
    "\"=\"",
    "\">]\"",
    "\">}\"",
    "\"?\"",
    "\"[\"",
    "\"[<\"",
    "\">\"",
    "\"]\"",
    "\"_\"",
    "\"`\"",
    "\"{\"",
    "\"{<\"",
    "\"|\"",
    "\"|]\"",
    "\"||\"",
    "\"}\"",
    "\"~\"",
    "\"-\"",
    "\";;\"",
    "\"[|\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"**\"",
    "\"/.\"",
    "\"*.\"",
    "\"~-.\"",
    "\"+.\"",
    "\"/\"",
    "\"~-\"",
    "\"@\"",
    "\"^\"",
    "<LINENUM_DIRECTIVE>",
    "<ID>",
    "<LETRA>",
    "<DIGITO>",
    "<LOWER_ID>",
    "<UPPER_ID>",
    "<CHAR_OPERADOR_CORE>",
    "<CHAR_OPERADOR>",
    "<PREFIX_SYMBOL>",
    "<INFIX_SYMBOL>",
  };

}
