/* Generated By:JavaCC: Do not edit this line. OcamlParserTokenManager.java */
import java.io.FileWriter;
import java.io.IOException;

/** Token Manager. */
public class OcamlParserTokenManager implements OcamlParserConstants
{
    static int commentNestingDepth;

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0xfffffffffe000000L) != 0L || (active1 & 0x1ffffL) != 0L)
         {
            jjmatchedKind = 136;
            return 55;
         }
         if ((active1 & 0x80000000000000L) != 0L || (active2 & 0x12L) != 0L)
            return 173;
         if ((active1 & 0x40000L) != 0L)
            return 174;
         if ((active1 & 0xf83823e003180000L) != 0L || (active2 & 0x6dL) != 0L)
            return 61;
         if ((active1 & 0x800000000000L) != 0L)
            return 55;
         if ((active1 & 0x200000L) != 0L)
            return 1;
         if ((active1 & 0x40000000000L) != 0L)
            return 175;
         if ((active1 & 0x20000L) != 0L)
         {
            jjmatchedKind = 143;
            return 57;
         }
         if ((active1 & 0x100000018000000L) != 0L)
            return 155;
         return -1;
      case 1:
         if ((active1 & 0xf820004018100000L) != 0L || (active2 & 0x5L) != 0L)
            return 61;
         if ((active0 & 0xfbffe1fc62000000L) != 0L || (active1 & 0x137ffL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 136;
               jjmatchedPos = 1;
            }
            return 55;
         }
         if ((active0 & 0x4001e039c000000L) != 0L || (active1 & 0xc800L) != 0L)
            return 55;
         if ((active1 & 0x20000L) != 0L)
            return 57;
         if ((active2 & 0x12L) != 0L)
            return 59;
         return -1;
      case 2:
         if ((active0 & 0x60e381c012000000L) != 0L || (active1 & 0x1614L) != 0L)
            return 55;
         if ((active2 & 0x2L) != 0L)
            return 59;
         if ((active0 & 0x9b1c783f68000000L) != 0L || (active1 & 0x129ebL) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 136;
               jjmatchedPos = 2;
            }
            return 55;
         }
         return -1;
      case 3:
         if ((active0 & 0x804600500000000L) != 0L || (active1 & 0x1008bL) != 0L)
            return 55;
         if ((active0 & 0x9358193a68000000L) != 0L || (active1 & 0x2d60L) != 0L)
         {
            jjmatchedKind = 136;
            jjmatchedPos = 3;
            return 55;
         }
         return -1;
      case 4:
         if ((active0 & 0x9350191a48000000L) != 0L || (active1 & 0x2c20L) != 0L)
         {
            jjmatchedKind = 136;
            jjmatchedPos = 4;
            return 55;
         }
         if ((active0 & 0x8002020000000L) != 0L || (active1 & 0x140L) != 0L)
            return 55;
         return -1;
      case 5:
         if ((active0 & 0x1000191840000000L) != 0L || (active1 & 0x2c20L) != 0L)
         {
            jjmatchedKind = 136;
            jjmatchedPos = 5;
            return 55;
         }
         if ((active0 & 0x8350000208000000L) != 0L)
            return 55;
         return -1;
      case 6:
         if ((active0 & 0x1000190000000000L) != 0L || (active1 & 0x2020L) != 0L)
            return 55;
         if ((active0 & 0x1840000000L) != 0L || (active1 & 0xc00L) != 0L)
         {
            jjmatchedKind = 136;
            jjmatchedPos = 6;
            return 55;
         }
         return -1;
      case 7:
         if ((active0 & 0x840000000L) != 0L || (active1 & 0x800L) != 0L)
         {
            jjmatchedKind = 136;
            jjmatchedPos = 7;
            return 55;
         }
         if ((active0 & 0x1000000000L) != 0L || (active1 & 0x400L) != 0L)
            return 55;
         return -1;
      case 8:
         if ((active0 & 0x800000000L) != 0L)
            return 55;
         if ((active0 & 0x40000000L) != 0L || (active1 & 0x800L) != 0L)
         {
            jjmatchedKind = 136;
            jjmatchedPos = 8;
            return 55;
         }
         return -1;
      case 9:
         if ((active0 & 0x40000000L) != 0L)
            return 55;
         if ((active1 & 0x800L) != 0L)
         {
            jjmatchedKind = 136;
            jjmatchedPos = 9;
            return 55;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0, long active1, long active2)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20000L, 0x0L);
      case 35:
         return jjStartNfaWithStates_0(0, 82, 174);
      case 38:
         jjmatchedKind = 83;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100000L, 0x0L);
      case 39:
         return jjStartNfaWithStates_0(0, 85, 1);
      case 40:
         jjmatchedKind = 86;
         return jjMoveStringLiteralDfa1_0(0x2L, 0x0L, 0x0L);
      case 41:
         return jjStopAtPos(0, 87);
      case 42:
         jjmatchedKind = 88;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4000000000000000L, 0x1L);
      case 43:
         jjmatchedKind = 89;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x4L);
      case 44:
         return jjStopAtPos(0, 90);
      case 45:
         jjmatchedKind = 120;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x18000000L, 0x0L);
      case 46:
         jjmatchedKind = 93;
         return jjMoveStringLiteralDfa1_0(0x0L, 0xc0000000L, 0x0L);
      case 47:
         jjmatchedKind = 131;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8000000000000000L, 0x0L);
      case 58:
         jjmatchedKind = 96;
         return jjMoveStringLiteralDfa1_0(0x0L, 0xe00000000L, 0x0L);
      case 59:
         jjmatchedKind = 100;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200000000000000L, 0x0L);
      case 60:
         jjmatchedKind = 101;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1000004000000000L, 0x0L);
      case 61:
         jjmatchedKind = 103;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2000000000000000L, 0x0L);
      case 62:
         jjmatchedKind = 109;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800030000000000L, 0x0L);
      case 63:
         return jjStartNfaWithStates_0(0, 106, 175);
      case 64:
         return jjStartNfaWithStates_0(0, 133, 61);
      case 91:
         jjmatchedKind = 107;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400100000000000L, 0x0L);
      case 93:
         return jjStopAtPos(0, 110);
      case 94:
         return jjStartNfaWithStates_0(0, 134, 61);
      case 95:
         return jjStartNfaWithStates_0(0, 111, 55);
      case 96:
         return jjStopAtPos(0, 112);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x1e000000L, 0x0L, 0x0L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x20000000L, 0x0L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x40000000L, 0x100L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x380000000L, 0x0L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x1c00000000L, 0x200L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x1e000000000L, 0x400L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x1e0000000000L, 0x800L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x7e00000000000L, 0x1000L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x78000000000000L, 0x2000L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x180000000000000L, 0x0L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0xe00000000000000L, 0x4000L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x1000000000000000L, 0x0L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x2000000000000000L, 0x0L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0xc000000000000000L, 0x0L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800fL, 0x0L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x30L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100c0L, 0x0L);
      case 123:
         jjmatchedKind = 113;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4000000000000L, 0x0L);
      case 124:
         jjmatchedKind = 115;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x30000000000000L, 0x0L);
      case 125:
         return jjStopAtPos(0, 118);
      case 126:
         jjmatchedKind = 119;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x12L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0, long active1, long active2)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1, active2);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(1, 84, 61);
         break;
      case 42:
         if ((active0 & 0x2L) != 0L)
            return jjStopAtPos(1, 1);
         else if ((active1 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 126, 61);
         break;
      case 45:
         if ((active1 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 102, 61);
         else if ((active2 & 0x10L) != 0L)
         {
            jjmatchedKind = 132;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0L, active2, 0x2L);
      case 46:
         if ((active1 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(1, 91, 61);
         else if ((active1 & 0x40000000L) != 0L)
            return jjStopAtPos(1, 94);
         else if ((active1 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 127, 61);
         else if ((active2 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(1, 128, 61);
         else if ((active2 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(1, 130, 61);
         break;
      case 58:
         if ((active1 & 0x200000000L) != 0L)
            return jjStopAtPos(1, 97);
         break;
      case 59:
         if ((active1 & 0x200000000000000L) != 0L)
            return jjStopAtPos(1, 121);
         break;
      case 60:
         if ((active1 & 0x100000000000L) != 0L)
            return jjStopAtPos(1, 108);
         else if ((active1 & 0x4000000000000L) != 0L)
            return jjStopAtPos(1, 114);
         break;
      case 61:
         if ((active1 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(1, 81, 57);
         else if ((active1 & 0x400000000L) != 0L)
            return jjStopAtPos(1, 98);
         else if ((active1 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 123, 61);
         else if ((active1 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 124, 61);
         else if ((active1 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 125, 61);
         break;
      case 62:
         if ((active1 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(1, 92, 61);
         else if ((active1 & 0x800000000L) != 0L)
            return jjStopAtPos(1, 99);
         break;
      case 93:
         if ((active1 & 0x10000000000L) != 0L)
            return jjStopAtPos(1, 104);
         else if ((active1 & 0x10000000000000L) != 0L)
            return jjStopAtPos(1, 116);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x8602000000000L, active1, 0x10L, active2, 0L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000000000000L, active1, 0L, active2, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x2090800020000000L, active1, 0L, active2, 0L);
      case 102:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 41, 55);
         else if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 58, 55);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x10041L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000000000L, active1, 0xa0L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000000L, active1, 0x100L, active2, 0L);
      case 110:
         if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 42;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x180002000000L, active1, 0xa00L, active2, 0L);
      case 111:
         if ((active0 & 0x80000000L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(1, 79, 55);
         return jjMoveStringLiteralDfa2_0(active0, 0x161004340000000L, active1, 0L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000000000L, active1, 0L, active2, 0L);
      case 114:
         if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(1, 78, 55);
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000000000L, active1, 0x6L, active2, 0L);
      case 115:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x2000018000000L, active1, 0x1000L, active2, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000000000L, active1, 0L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x18000000000L, active1, 0x2400L, active2, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x4001800000000L, active1, 0L, active2, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x8L, active2, 0L);
      case 124:
         if ((active1 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 117, 61);
         else if ((active1 & 0x400000000000000L) != 0L)
            return jjStopAtPos(1, 122);
         break;
      case 125:
         if ((active1 & 0x20000000000L) != 0L)
            return jjStopAtPos(1, 105);
         break;
      case 126:
         if ((active1 & 0x80000000L) != 0L)
            return jjStopAtPos(1, 95);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(0, old0, old1, old2); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1, active2);
      return 2;
   }
   switch(curChar)
   {
      case 46:
         if ((active2 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(2, 129, 59);
         break;
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x100L, active2, 0L);
      case 99:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 61, 55);
         return jjMoveStringLiteralDfa3_0(active0, 0x80800000000L, active1, 0L, active2, 0L);
      case 100:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(2, 25, 55);
         else if ((active0 & 0x20000000000000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(2, 73, 55);
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000000L, active1, 0L, active2, 0L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000000000L, active1, 0x10001L, active2, 0L);
      case 103:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 62, 55);
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000L, active1, 0L, active2, 0L);
      case 104:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000L, active1, 0L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000000000L, active1, 0x840L, active2, 0L);
      case 106:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000000000L, active1, 0L, active2, 0L);
      case 108:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 49, 55);
         else if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(2, 68, 55);
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000L, active1, 0L, active2, 0L);
      case 110:
         if ((active0 & 0x8000000000L) != 0L)
         {
            jjmatchedKind = 39;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x100210140000000L, active1, 0x400L, active2, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000000L, active1, 0L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x8L, active2, 0L);
      case 114:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(2, 28, 55);
         else if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 38, 55);
         else if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 48, 55);
         else if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(2, 76, 55);
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000000000L, active1, 0x20L, active2, 0L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x408000000L, active1, 0L, active2, 0L);
      case 116:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 47, 55);
         return jjMoveStringLiteralDfa3_0(active0, 0x18001000000000L, active1, 0x2080L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x2L, active2, 0L);
      case 119:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 55, 55);
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000L, active1, 0L, active2, 0L);
      case 121:
         if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(2, 66, 55);
         break;
      case 122:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000000L, active1, 0L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1, active2);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(1, old0, old1, old2); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1, 0L);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x2000L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x8010000000000L, active1, 0x400L);
      case 100:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 45, 55);
         break;
      case 101:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(3, 32, 55);
         else if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(3, 34, 55);
         else if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(3, 65, 55);
         else if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(3, 67, 55);
         return jjMoveStringLiteralDfa4_0(active0, 0x200101808000000L, active1, 0L);
      case 104:
         if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(3, 71, 55);
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000000L, active1, 0x40L);
      case 110:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 59, 55);
         else if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(3, 64, 55);
         else if ((active1 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(3, 80, 55);
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000L, active1, 0L);
      case 114:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 50, 55);
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000000000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x2040000000L, active1, 0x100L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x820L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x8040000000000000L, active1, 0L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000000000L, active1, 0L);
      case 121:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 46, 55);
         break;
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1, 0L);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1, 0L);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000000000L, active1, 0L);
      case 98:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x2000L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x8200000000000000L, active1, 0L);
      case 101:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 37, 55);
         else if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(4, 70, 55);
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000000000L, active1, 0L);
      case 104:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 51, 55);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x800L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000000000L, active1, 0L);
      case 110:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(4, 29, 55);
         break;
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000000000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x101008000000L, active1, 0L);
      case 115:
         if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(4, 72, 55);
         break;
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x10240000000L, active1, 0x400L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000000L, active1, 0x20L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1, 0L);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x820L);
      case 99:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 56, 55);
         break;
      case 100:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 52, 55);
         return jjMoveStringLiteralDfa6_0(active0, 0x80000000000L, active1, 0L);
      case 101:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 54, 55);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000000L, active1, 0x400L);
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x2000L);
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000000L, active1, 0L);
      case 111:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(5, 33, 55);
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000L, active1, 0L);
      case 116:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(5, 27, 55);
         else if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 57, 55);
         else if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 63, 55);
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000800000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1, 0L);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x1040000000L, active1, 0L);
      case 101:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 43, 55);
         else if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 60, 55);
         else if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(6, 77, 55);
         break;
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000L, active1, 0L);
      case 108:
         if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(6, 69, 55);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x800L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x400L);
      case 114:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 40, 55);
         break;
      case 116:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 44, 55);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1, 0L);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000000L, active1, 0x800L);
      case 108:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 36, 55);
         break;
      case 110:
         if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(7, 74, 55);
         break;
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0x800000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1, 0L);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 110:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(8, 35, 55);
         return jjMoveStringLiteralDfa9_0(active0, 0x40000000L, active1, 0L);
      case 122:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x800L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1, 0L);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x800L);
      case 116:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(9, 30, 55);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1, 0L);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(8, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, 0L, active1, 0L);
      return 10;
   }
   switch(curChar)
   {
      case 114:
         if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(10, 75, 55);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, 0L, active1, 0L);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   //int[] nextStates; // not used
   int startsAt = 0;
   jjnewStateCnt = 173;
   int i = 1;
   jjstateSet[0] = startState;
   //int j; // not used
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAdd(2);
                  break;
               case 155:
                  if ((0xf400ec7000000000L & l) != 0L)
                  {
                     if (kind > 144)
                        kind = 144;
                     jjCheckNAdd(61);
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(70, 71);
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 9)
                        kind = 9;
                     jjCheckNAdd(69);
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(67, 68);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(65, 66);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(63, 64);
                  if (curChar == 48)
                     jjCheckNAddTwoStates(100, 103);
                  if (curChar == 48)
                     jjCheckNAddTwoStates(104, 107);
                  if (curChar == 48)
                     jjCheckNAddTwoStates(108, 110);
                  if (curChar == 48)
                     jjCheckNAddTwoStates(111, 114);
                  if (curChar == 48)
                     jjCheckNAddTwoStates(115, 118);
                  if (curChar == 48)
                     jjCheckNAddTwoStates(119, 121);
                  if (curChar == 48)
                     jjCheckNAddTwoStates(122, 125);
                  if (curChar == 48)
                     jjCheckNAddTwoStates(126, 129);
                  if (curChar == 48)
                     jjCheckNAddTwoStates(130, 132);
                  if (curChar == 48)
                     jjCheckNAddTwoStates(133, 135);
                  if (curChar == 48)
                     jjCheckNAddTwoStates(136, 139);
                  if (curChar == 48)
                     jjCheckNAddTwoStates(140, 143);
                  if (curChar == 48)
                     jjCheckNAddTwoStates(144, 153);
                  break;
               case 174:
                  if ((0xf400ec7000000000L & l) != 0L)
                  {
                     if (kind > 144)
                        kind = 144;
                     jjCheckNAdd(98);
                  }
                  else if (curChar == 32)
                     jjCheckNAddTwoStates(77, 78);
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 9)
                        kind = 9;
                     jjCheckNAddStates(0, 8);
                  }
                  else if ((0x7000ac7000000000L & l) != 0L)
                  {
                     if (kind > 144)
                        kind = 144;
                     jjCheckNAdd(61);
                  }
                  else if (curChar == 35)
                     jjCheckNAddTwoStates(77, 98);
                  else if (curChar == 33)
                  {
                     if (kind > 143)
                        kind = 143;
                     jjCheckNAdd(57);
                  }
                  else if (curChar == 34)
                     jjCheckNAddStates(9, 12);
                  else if (curChar == 39)
                     jjAddStates(13, 15);
                  else if (curChar == 63)
                     jjCheckNAdd(59);
                  if (curChar == 45)
                     jjAddStates(16, 33);
                  else if (curChar == 48)
                     jjCheckNAddStates(34, 59);
                  else if (curChar == 63)
                     jjCheckNAddStates(60, 62);
                  break;
               case 173:
                  if ((0xf400ec7000000000L & l) != 0L)
                  {
                     if (kind > 143)
                        kind = 143;
                     jjCheckNAdd(59);
                  }
                  else if (curChar == 32)
                     jjCheckNAddStates(63, 65);
                  break;
               case 175:
                  if ((0xf400ec7000000000L & l) != 0L)
                  {
                     if (kind > 143)
                        kind = 143;
                     jjCheckNAdd(59);
                  }
                  else if (curChar == 32)
                     jjCheckNAddStates(60, 62);
                  break;
               case 2:
                  if (curChar == 39 && kind > 20)
                     kind = 20;
                  break;
               case 4:
                  if ((0x8500000000L & l) != 0L)
                     jjCheckNAdd(2);
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 7:
               case 15:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(2);
                  break;
               case 10:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 11:
                  if ((0xff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 12:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAdd(2);
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 16:
                  if (curChar == 34)
                     jjCheckNAddStates(9, 12);
                  break;
               case 17:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddStates(9, 12);
                  break;
               case 18:
                  if (curChar == 34 && kind > 22)
                     kind = 22;
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(66, 70);
                  break;
               case 23:
                  if ((0x8500000000L & l) != 0L)
                     jjCheckNAddStates(9, 12);
                  break;
               case 24:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 26:
               case 33:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(9, 12);
                  break;
               case 28:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 29:
                  if ((0xff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 30:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(9, 12);
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 35:
                  if (curChar == 32)
                     jjCheckNAddStates(63, 65);
                  break;
               case 39:
                  if ((0x3ff008000000000L & l) != 0L)
                     jjCheckNAddStates(71, 74);
                  break;
               case 40:
                  if (curChar == 32)
                     jjCheckNAddStates(75, 77);
                  break;
               case 43:
                  if (curChar == 58 && kind > 23)
                     kind = 23;
                  break;
               case 44:
                  if (curChar == 63)
                     jjCheckNAddStates(60, 62);
                  break;
               case 45:
                  if (curChar == 32)
                     jjCheckNAddStates(60, 62);
                  break;
               case 49:
                  if ((0x3ff008000000000L & l) != 0L)
                     jjCheckNAddStates(78, 81);
                  break;
               case 50:
                  if (curChar == 32)
                     jjCheckNAddStates(82, 84);
                  break;
               case 53:
                  if (curChar == 58 && kind > 24)
                     kind = 24;
                  break;
               case 55:
                  if ((0x3ff008000000000L & l) == 0L)
                     break;
                  if (kind > 136)
                     kind = 136;
                  jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 56:
                  if (curChar != 33)
                     break;
                  if (kind > 143)
                     kind = 143;
                  jjCheckNAdd(57);
                  break;
               case 57:
                  if ((0xf400ec7000000000L & l) == 0L)
                     break;
                  if (kind > 143)
                     kind = 143;
                  jjCheckNAdd(57);
                  break;
               case 58:
                  if (curChar == 63)
                     jjCheckNAdd(59);
                  break;
               case 59:
                  if ((0xf400ec7000000000L & l) == 0L)
                     break;
                  if (kind > 143)
                     kind = 143;
                  jjCheckNAdd(59);
                  break;
               case 60:
                  if ((0x7000ac7000000000L & l) == 0L)
                     break;
                  if (kind > 144)
                     kind = 144;
                  jjCheckNAdd(61);
                  break;
               case 61:
                  if ((0xf400ec7000000000L & l) == 0L)
                     break;
                  if (kind > 144)
                     kind = 144;
                  jjCheckNAdd(61);
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAddStates(0, 8);
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(63, 64);
                  break;
               case 65:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(65, 66);
                  break;
               case 67:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(67, 68);
                  break;
               case 69:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAdd(69);
                  break;
               case 70:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(70, 71);
                  break;
               case 71:
                  if (curChar != 46)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjCheckNAddTwoStates(72, 73);
                  break;
               case 72:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjCheckNAddTwoStates(72, 73);
                  break;
               case 74:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(75);
                  break;
               case 75:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjCheckNAdd(75);
                  break;
               case 76:
                  if (curChar == 35)
                     jjCheckNAddTwoStates(77, 98);
                  break;
               case 77:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(77, 78);
                  break;
               case 78:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(78, 79);
                  break;
               case 79:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(79, 80);
                  break;
               case 80:
                  if (curChar == 34)
                     jjCheckNAddStates(85, 88);
                  break;
               case 81:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddStates(85, 88);
                  break;
               case 82:
                  if (curChar == 34 && kind > 135)
                     kind = 135;
                  break;
               case 85:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(89, 93);
                  break;
               case 87:
                  if ((0x8500000000L & l) != 0L)
                     jjCheckNAddStates(85, 88);
                  break;
               case 88:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 89:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 90:
               case 97:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(85, 88);
                  break;
               case 92:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 93:
                  if ((0xff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 94:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(85, 88);
                  break;
               case 96:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 98:
                  if ((0xf400ec7000000000L & l) == 0L)
                     break;
                  if (kind > 144)
                     kind = 144;
                  jjCheckNAdd(98);
                  break;
               case 99:
                  if (curChar == 48)
                     jjCheckNAddStates(34, 59);
                  break;
               case 101:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(102, 64);
                  break;
               case 102:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddTwoStates(102, 64);
                  break;
               case 105:
               case 106:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(106, 64);
                  break;
               case 109:
                  if ((0x3000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(109, 64);
                  break;
               case 112:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(113, 66);
                  break;
               case 113:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddTwoStates(113, 66);
                  break;
               case 116:
               case 117:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(117, 66);
                  break;
               case 120:
                  if ((0x3000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(120, 66);
                  break;
               case 123:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(124, 68);
                  break;
               case 124:
                  if ((0x3ff200000000000L & l) != 0L)
                     jjCheckNAddTwoStates(124, 68);
                  break;
               case 127:
               case 128:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(128, 68);
                  break;
               case 131:
                  if ((0x3000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(131, 68);
                  break;
               case 134:
                  if ((0x3000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 137:
               case 138:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAdd(138);
                  break;
               case 141:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAdd(142);
                  break;
               case 142:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAdd(142);
                  break;
               case 145:
               case 146:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(146, 147);
                  break;
               case 147:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 148:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 150:
                  if ((0x280000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 151:
               case 152:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjCheckNAdd(152);
                  break;
               case 154:
                  if (curChar == 45)
                     jjAddStates(16, 33);
                  break;
               case 156:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(65, 66);
                  break;
               case 157:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(67, 68);
                  break;
               case 158:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAdd(69);
                  break;
               case 159:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(70, 71);
                  break;
               case 160:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(144, 153);
                  break;
               case 161:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(140, 143);
                  break;
               case 162:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(136, 139);
                  break;
               case 163:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(133, 135);
                  break;
               case 164:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(130, 132);
                  break;
               case 165:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(126, 129);
                  break;
               case 166:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(122, 125);
                  break;
               case 167:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(119, 121);
                  break;
               case 168:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(115, 118);
                  break;
               case 169:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(111, 114);
                  break;
               case 170:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(108, 110);
                  break;
               case 171:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(104, 107);
                  break;
               case 172:
                  if (curChar == 48)
                     jjCheckNAddTwoStates(100, 103);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAdd(2);
                  else if (curChar == 92)
                     jjAddStates(94, 95);
                  if (curChar == 92)
                     jjAddStates(96, 97);
                  break;
               case 155:
               case 61:
                  if ((0x5000000040000001L & l) == 0L)
                     break;
                  if (kind > 144)
                     kind = 144;
                  jjCheckNAdd(61);
                  break;
               case 174:
               case 98:
                  if ((0x5000000040000001L & l) == 0L)
                     break;
                  if (kind > 144)
                     kind = 144;
                  jjCheckNAdd(98);
                  break;
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 136)
                        kind = 136;
                     jjCheckNAdd(55);
                  }
                  else if ((0x1000000040000001L & l) != 0L)
                  {
                     if (kind > 144)
                        kind = 144;
                     jjCheckNAdd(61);
                  }
                  else if (curChar == 126)
                     jjCheckNAdd(59);
                  if (curChar == 126)
                     jjCheckNAddStates(63, 65);
                  break;
               case 173:
                  if ((0x7fffffe80000000L & l) != 0L)
                     jjCheckNAddStates(71, 74);
                  else if ((0x5000000040000001L & l) != 0L)
                  {
                     if (kind > 143)
                        kind = 143;
                     jjCheckNAdd(59);
                  }
                  else if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 175:
                  if ((0x7fffffe80000000L & l) != 0L)
                     jjCheckNAddStates(78, 81);
                  else if ((0x5000000040000001L & l) != 0L)
                  {
                     if (kind > 143)
                        kind = 143;
                     jjCheckNAdd(59);
                  }
                  else if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 3:
                  if (curChar == 92)
                     jjAddStates(96, 97);
                  break;
               case 4:
                  if ((0x14400410000000L & l) != 0L)
                     jjCheckNAdd(2);
                  break;
               case 8:
                  if (curChar == 92)
                     jjAddStates(94, 95);
                  break;
               case 9:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 13:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 14:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 15:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAdd(2);
                  break;
               case 17:
                  jjCheckNAddStates(9, 12);
                  break;
               case 19:
                  if (curChar == 92)
                     jjAddStates(98, 100);
                  break;
               case 20:
                  if (curChar == 117)
                     jjCheckNAddStates(66, 70);
                  break;
               case 21:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(66, 70);
                  break;
               case 22:
                  if (curChar == 92)
                     jjAddStates(101, 102);
                  break;
               case 23:
                  if ((0x14400410000000L & l) != 0L)
                     jjCheckNAddStates(9, 12);
                  break;
               case 27:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 31:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 32:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 33:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(9, 12);
                  break;
               case 34:
                  if (curChar == 126)
                     jjCheckNAddStates(63, 65);
                  break;
               case 36:
                  if (curChar == 116)
                     jjCheckNAddStates(63, 65);
                  break;
               case 37:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 38:
                  if ((0x7fffffe80000000L & l) != 0L)
                     jjCheckNAddStates(71, 74);
                  break;
               case 39:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(71, 74);
                  break;
               case 41:
                  if (curChar == 116)
                     jjCheckNAddStates(75, 77);
                  break;
               case 42:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 46:
                  if (curChar == 116)
                     jjAddStates(60, 62);
                  break;
               case 47:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 48:
                  if ((0x7fffffe80000000L & l) != 0L)
                     jjCheckNAddStates(78, 81);
                  break;
               case 49:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(78, 81);
                  break;
               case 51:
                  if (curChar == 116)
                     jjCheckNAddStates(82, 84);
                  break;
               case 52:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 54:
               case 55:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 136)
                     kind = 136;
                  jjCheckNAdd(55);
                  break;
               case 57:
                  if ((0x5000000040000001L & l) == 0L)
                     break;
                  if (kind > 143)
                     kind = 143;
                  jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 58:
                  if (curChar == 126)
                     jjCheckNAdd(59);
                  break;
               case 59:
                  if ((0x5000000040000001L & l) == 0L)
                     break;
                  if (kind > 143)
                     kind = 143;
                  jjCheckNAdd(59);
                  break;
               case 60:
                  if ((0x1000000040000001L & l) == 0L)
                     break;
                  if (kind > 144)
                     kind = 144;
                  jjCheckNAdd(61);
                  break;
               case 63:
                  if (curChar == 95)
                     jjCheckNAddTwoStates(63, 64);
                  break;
               case 64:
                  if (curChar == 108 && kind > 9)
                     kind = 9;
                  break;
               case 65:
                  if (curChar == 95)
                     jjCheckNAddTwoStates(65, 66);
                  break;
               case 66:
                  if (curChar == 76 && kind > 9)
                     kind = 9;
                  break;
               case 67:
                  if (curChar == 95)
                     jjCheckNAddTwoStates(67, 68);
                  break;
               case 68:
                  if (curChar == 110 && kind > 9)
                     kind = 9;
                  break;
               case 69:
                  if (curChar != 95)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 70:
                  if (curChar == 95)
                     jjAddStates(103, 104);
                  break;
               case 72:
                  if (curChar != 95)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjAddStates(105, 106);
                  break;
               case 73:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(107, 108);
                  break;
               case 81:
                  jjCheckNAddStates(85, 88);
                  break;
               case 83:
                  if (curChar == 92)
                     jjAddStates(109, 111);
                  break;
               case 84:
                  if (curChar == 117)
                     jjCheckNAddStates(89, 93);
                  break;
               case 85:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(89, 93);
                  break;
               case 86:
                  if (curChar == 92)
                     jjAddStates(112, 113);
                  break;
               case 87:
                  if ((0x14400410000000L & l) != 0L)
                     jjCheckNAddStates(85, 88);
                  break;
               case 91:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 95:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 96:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 97:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(85, 88);
                  break;
               case 100:
                  if (curChar == 120)
                     jjCheckNAdd(101);
                  break;
               case 101:
               case 102:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(102, 64);
                  break;
               case 103:
                  if (curChar == 88)
                     jjCheckNAdd(101);
                  break;
               case 104:
                  if (curChar == 111)
                     jjCheckNAdd(105);
                  break;
               case 106:
                  if (curChar == 95)
                     jjCheckNAddTwoStates(106, 64);
                  break;
               case 107:
                  if (curChar == 79)
                     jjCheckNAdd(105);
                  break;
               case 108:
                  if (curChar == 98)
                     jjCheckNAdd(109);
                  break;
               case 110:
                  if (curChar == 66)
                     jjCheckNAdd(109);
                  break;
               case 111:
                  if (curChar == 120)
                     jjCheckNAdd(112);
                  break;
               case 112:
               case 113:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(113, 66);
                  break;
               case 114:
                  if (curChar == 88)
                     jjCheckNAdd(112);
                  break;
               case 115:
                  if (curChar == 111)
                     jjCheckNAdd(116);
                  break;
               case 117:
                  if (curChar == 95)
                     jjCheckNAddTwoStates(117, 66);
                  break;
               case 118:
                  if (curChar == 79)
                     jjCheckNAdd(116);
                  break;
               case 119:
                  if (curChar == 98)
                     jjCheckNAdd(120);
                  break;
               case 121:
                  if (curChar == 66)
                     jjCheckNAdd(120);
                  break;
               case 122:
                  if (curChar == 120)
                     jjCheckNAdd(123);
                  break;
               case 123:
               case 124:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(124, 68);
                  break;
               case 125:
                  if (curChar == 88)
                     jjCheckNAdd(123);
                  break;
               case 126:
                  if (curChar == 111)
                     jjCheckNAdd(127);
                  break;
               case 128:
                  if (curChar == 95)
                     jjCheckNAddTwoStates(128, 68);
                  break;
               case 129:
                  if (curChar == 79)
                     jjCheckNAdd(127);
                  break;
               case 130:
                  if (curChar == 98)
                     jjCheckNAdd(131);
                  break;
               case 132:
                  if (curChar == 66)
                     jjCheckNAdd(131);
                  break;
               case 133:
                  if (curChar == 98)
                     jjCheckNAdd(134);
                  break;
               case 135:
                  if (curChar == 66)
                     jjCheckNAdd(134);
                  break;
               case 136:
                  if (curChar == 111)
                     jjCheckNAdd(137);
                  break;
               case 138:
                  if (curChar != 95)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 139:
                  if (curChar == 79)
                     jjCheckNAdd(137);
                  break;
               case 140:
                  if (curChar == 120)
                     jjCheckNAdd(141);
                  break;
               case 141:
               case 142:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAdd(142);
                  break;
               case 143:
                  if (curChar == 88)
                     jjCheckNAdd(141);
                  break;
               case 144:
                  if (curChar == 120)
                     jjCheckNAdd(145);
                  break;
               case 145:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(146, 147);
                  break;
               case 146:
                  if ((0x7e8000007eL & l) != 0L)
                     jjCheckNAddTwoStates(146, 147);
                  break;
               case 148:
                  if ((0x7e8000007eL & l) == 0L)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 149:
                  if ((0x1000000010000L & l) != 0L)
                     jjAddStates(114, 115);
                  break;
               case 152:
                  if (curChar != 95)
                     break;
                  if (kind > 18)
                     kind = 18;
                  jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 153:
                  if (curChar == 88)
                     jjCheckNAdd(145);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 17:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(9, 12);
                  break;
               case 81:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(85, 88);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 173 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static private int jjMoveStringLiteralDfa0_1()
{
   switch(curChar)
   {
      case 40:
         return jjMoveStringLiteralDfa1_1(0x4L);
      case 42:
         return jjMoveStringLiteralDfa1_1(0x8L);
      default :
         return 1;
   }
}
static private int jjMoveStringLiteralDfa1_1(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 41:
         if ((active0 & 0x8L) != 0L)
            return jjStopAtPos(1, 3);
         break;
      case 42:
         if ((active0 & 0x4L) != 0L)
            return jjStopAtPos(1, 2);
         break;
      default :
         return 2;
   }
   return 2;
}
static final int[] jjnextStates = {
   63, 64, 65, 66, 67, 68, 69, 70, 71, 17, 18, 19, 22, 1, 3, 8, 
   155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 
   171, 172, 100, 103, 104, 107, 108, 110, 111, 114, 115, 118, 119, 121, 122, 125, 
   126, 129, 130, 132, 133, 135, 136, 139, 140, 143, 144, 153, 45, 47, 48, 35, 
   37, 38, 17, 21, 18, 19, 22, 39, 40, 42, 43, 40, 42, 43, 49, 50, 
   52, 53, 50, 52, 53, 81, 82, 83, 86, 81, 85, 82, 83, 86, 9, 13, 
   4, 5, 20, 27, 31, 23, 24, 70, 71, 72, 73, 74, 75, 84, 91, 95, 
   87, 88, 150, 151, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, 
"\141\156\144", "\141\163", "\141\163\163\145\162\164", "\141\163\162", 
"\142\145\147\151\156", "\143\157\156\163\164\162\141\151\156\164", "\144\157", "\144\157\156\145", 
"\144\157\167\156\164\157", "\145\154\163\145", "\145\170\143\145\160\164\151\157\156", 
"\145\170\164\145\162\156\141\154", "\146\141\154\163\145", "\146\157\162", "\146\165\156", 
"\146\165\156\143\164\157\162", "\151\146", "\151\156", "\151\156\143\154\165\144\145", 
"\151\156\150\145\162\151\164", "\154\141\156\144", "\154\141\172\171", "\154\145\164", "\154\157\162", 
"\154\163\154", "\154\170\157\162", "\155\141\164\143\150", "\155\145\164\150\157\144", 
"\155\157\144", "\155\157\144\165\154\145", "\156\145\167", "\156\157\156\162\145\143", 
"\157\142\152\145\143\164", "\157\146", "\157\160\145\156", "\160\162\151\166\141\164\145", 
"\162\145\143", "\163\151\147", "\163\164\162\165\143\164", "\164\150\145\156", 
"\164\162\165\145", "\164\162\171", "\164\171\160\145", "\166\141\154", 
"\166\151\162\164\165\141\154", "\167\150\151\154\145", "\167\151\164\150", "\143\154\141\163\163", 
"\145\156\144", "\146\165\156\143\164\151\157\156", 
"\151\156\151\164\151\141\154\151\172\145\162", "\154\163\162", "\155\165\164\141\142\154\145", "\157\162", "\164\157", 
"\167\150\145\156", "\41\75", "\43", "\46", "\46\46", "\47", "\50", "\51", "\52", "\53", "\54", 
"\55\56", "\55\76", "\56", "\56\56", "\56\176", "\72", "\72\72", "\72\75", "\72\76", 
"\73", "\74", "\74\55", "\75", "\76\135", "\76\175", "\77", "\133", "\133\74", "\76", 
"\135", "\137", "\140", "\173", "\173\74", "\174", "\174\135", "\174\174", "\175", 
"\176", "\55", "\73\73", "\133\174", "\76\75", "\74\75", "\75\75", "\52\52", "\57\56", 
"\52\56", "\176\55\56", "\53\56", "\57", "\176\55", "\100", "\136", null, null, null, 
null, null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT", 
   "COMMENT", 
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xffffffffffd40201L, 0xffffffffffffffffL, 0x181ffL, 
};
static final long[] jjtoSkip = {
   0x1feL, 0x0L, 0x0L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[173];
static private final int[] jjstateSet = new int[346];
static StringBuffer image;
static int jjimageLen;
static int lengthOfMatch;
static protected char curChar;
/** Constructor. */
public OcamlParserTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public OcamlParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 173; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 2 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String tokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   tokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, tokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  //int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = null;
   jjimageLen = 0;

   switch(curLexState)
   {
     case 0:
       try { input_stream.backup(0);
          while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
             curChar = input_stream.BeginToken();
       }
       catch (java.io.IOException e1) { continue EOFLoop; }
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_0();
       break;
     case 1:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_1();
       if (jjmatchedPos == 0 && jjmatchedKind > 4)
       {
          jjmatchedKind = 4;
       }
       break;
   }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else
        {
           SkipLexicalActions(null);
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 1 :
         if (image == null)
            image = new StringBuffer();
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
       commentNestingDepth=1;
         break;
      case 2 :
         if (image == null)
            image = new StringBuffer();
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                          commentNestingDepth += 1 ;
         break;
      case 3 :
         if (image == null)
            image = new StringBuffer();
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
    commentNestingDepth -= 1;
    SwitchTo( commentNestingDepth==0 ? DEFAULT : COMMENT ) ;
         break;
      default :
         break;
   }
}
static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
