/* Generated By:JavaCC: Do not edit this line. OcamlParser.java */
import java.io.FileWriter;
import java.io.IOException;

public class OcamlParser implements OcamlParserConstants {

  /** Main entry point. */
  public static void main(String args[]) throws ParseException, IOException {
    OcamlParser parser = new OcamlParser(System.in);
    parser.Input();
  }

  public static void printToken(String token, String lexema){
    System.out.println(token + " " + lexema);
  }

/** Top level production. */
  static final public void Input() throws ParseException {
      Token t;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
        t = jj_consume_token(INT);
               printToken("INT", t.image);
        break;
      case FLOAT:
        t = jj_consume_token(FLOAT);
                 printToken("FLOAT", t.image);
        break;
      case CHAR:
        t = jj_consume_token(CHAR);
                printToken("CHAR", t.image);
        break;
      case STRING:
        t = jj_consume_token(STRING);
                  printToken("STRING", t.image);
        break;
      case LABEL:
        t = jj_consume_token(LABEL);
                 printToken("LABEL", t.image);
        break;
      case OPTLABEL:
        t = jj_consume_token(OPTLABEL);
                    printToken("OPTLABEL", t.image);
        break;
      case AND:
        t = jj_consume_token(AND);
               printToken("AND", t.image);
        break;
      case AS:
        t = jj_consume_token(AS);
              printToken("AS", t.image);
        break;
      case ASSERT:
        t = jj_consume_token(ASSERT);
                  printToken("ASSERT", t.image);
        break;
      case ASR:
        t = jj_consume_token(ASR);
               printToken("ASR", t.image);
        break;
      case BEGIN:
        t = jj_consume_token(BEGIN);
                 printToken("BEGIN", t.image);
        break;
      case CONSTRAINT:
        t = jj_consume_token(CONSTRAINT);
                      printToken("CONSTRAINT", t.image);
        break;
      case DO:
        t = jj_consume_token(DO);
              printToken("DO", t.image);
        break;
      case DONE:
        t = jj_consume_token(DONE);
                printToken("DONE", t.image);
        break;
      case DOWNTO:
        t = jj_consume_token(DOWNTO);
                  printToken("DOWNTO", t.image);
        break;
      case ELSE:
        t = jj_consume_token(ELSE);
                printToken("ELSE", t.image);
        break;
      case EXCEPTION:
        t = jj_consume_token(EXCEPTION);
                     printToken("EXCEPTION", t.image);
        break;
      case EXTERNAL:
        t = jj_consume_token(EXTERNAL);
                    printToken("EXTERNAL", t.image);
        break;
      case FALSE:
        t = jj_consume_token(FALSE);
                 printToken("FALSE", t.image);
        break;
      case FOR:
        t = jj_consume_token(FOR);
               printToken("FOR", t.image);
        break;
      case FUN:
        t = jj_consume_token(FUN);
               printToken("FUN", t.image);
        break;
      case FUNCTOR:
        t = jj_consume_token(FUNCTOR);
                   printToken("FUNCTOR", t.image);
        break;
      case IF:
        t = jj_consume_token(IF);
              printToken("IF", t.image);
        break;
      case IN:
        t = jj_consume_token(IN);
              printToken("IN", t.image);
        break;
      case INCLUDE:
        t = jj_consume_token(INCLUDE);
                   printToken("INCLUDE", t.image);
        break;
      case INHERIT:
        t = jj_consume_token(INHERIT);
                   printToken("INHERIT", t.image);
        break;
      case LAND:
        t = jj_consume_token(LAND);
                printToken("LAND", t.image);
        break;
      case LAZY:
        t = jj_consume_token(LAZY);
                printToken("LAZY", t.image);
        break;
      case LET:
        t = jj_consume_token(LET);
               printToken("LET", t.image);
        break;
      case LOR:
        t = jj_consume_token(LOR);
               printToken("LOR", t.image);
        break;
      case LSL:
        t = jj_consume_token(LSL);
               printToken("LSL", t.image);
        break;
      case LXOR:
        t = jj_consume_token(LXOR);
                printToken("LXOR", t.image);
        break;
      case MATCH:
        t = jj_consume_token(MATCH);
                 printToken("MATCH", t.image);
        break;
      case METHOD:
        t = jj_consume_token(METHOD);
                  printToken("METHOD", t.image);
        break;
      case MOD:
        t = jj_consume_token(MOD);
               printToken("MOD", t.image);
        break;
      case MODULE:
        t = jj_consume_token(MODULE);
                  printToken("MODULE", t.image);
        break;
      case NEW:
        t = jj_consume_token(NEW);
               printToken("NEW", t.image);
        break;
      case NONREC:
        t = jj_consume_token(NONREC);
                  printToken("NONREC", t.image);
        break;
      case OBJECT:
        t = jj_consume_token(OBJECT);
                  printToken("OBJECT", t.image);
        break;
      case OF:
        t = jj_consume_token(OF);
              printToken("OF", t.image);
        break;
      case OPEN:
        t = jj_consume_token(OPEN);
                printToken("OPEN", t.image);
        break;
      case PRIVATE:
        t = jj_consume_token(PRIVATE);
                   printToken("PRIVATE", t.image);
        break;
      case REC:
        t = jj_consume_token(REC);
               printToken("REC", t.image);
        break;
      case SIG:
        t = jj_consume_token(SIG);
               printToken("SIG", t.image);
        break;
      case STRUCT:
        t = jj_consume_token(STRUCT);
                  printToken("STRUCT", t.image);
        break;
      case THEN:
        t = jj_consume_token(THEN);
                printToken("THEN", t.image);
        break;
      case TRUE:
        t = jj_consume_token(TRUE);
                printToken("TRUE", t.image);
        break;
      case TRY:
        t = jj_consume_token(TRY);
               printToken("TRY", t.image);
        break;
      case TYPE:
        t = jj_consume_token(TYPE);
                printToken("TYPE", t.image);
        break;
      case VAL:
        t = jj_consume_token(VAL);
               printToken("VAL", t.image);
        break;
      case VIRTUAL:
        t = jj_consume_token(VIRTUAL);
                   printToken("VIRTUAL", t.image);
        break;
      case WHILE:
        t = jj_consume_token(WHILE);
                 printToken("WHILE", t.image);
        break;
      case WITH:
        t = jj_consume_token(WITH);
                printToken("WITH", t.image);
        break;
      case CLASS:
        t = jj_consume_token(CLASS);
                 printToken("CLASS", t.image);
        break;
      case END:
        t = jj_consume_token(END);
               printToken("END", t.image);
        break;
      case FUNCTION:
        t = jj_consume_token(FUNCTION);
                    printToken("FUNCTION", t.image);
        break;
      case INITIALIZER:
        t = jj_consume_token(INITIALIZER);
                       printToken("INITIALIZER", t.image);
        break;
      case LSR:
        t = jj_consume_token(LSR);
               printToken("LSR", t.image);
        break;
      case MUTABLE:
        t = jj_consume_token(MUTABLE);
                   printToken("MUTABLE", t.image);
        break;
      case OR:
        t = jj_consume_token(OR);
              printToken("OR", t.image);
        break;
      case TO:
        t = jj_consume_token(TO);
              printToken("TO", t.image);
        break;
      case WHEN:
        t = jj_consume_token(WHEN);
                printToken("WHEN", t.image);
        break;
      case DIFF:
        t = jj_consume_token(DIFF);
                printToken("DIFF", t.image);
        break;
      case HASHTAG:
        t = jj_consume_token(HASHTAG);
                   printToken("HASHTAG", t.image);
        break;
      case EBIT:
        t = jj_consume_token(EBIT);
                printToken("EBIT", t.image);
        break;
      case ELOG:
        t = jj_consume_token(ELOG);
                printToken("ELOG", t.image);
        break;
      case ASPA:
        t = jj_consume_token(ASPA);
                printToken("ASPA", t.image);
        break;
      case EPAR:
        t = jj_consume_token(EPAR);
                printToken("EPAR", t.image);
        break;
      case DPAR:
        t = jj_consume_token(DPAR);
                printToken("DPAR", t.image);
        break;
      case AST:
        t = jj_consume_token(AST);
               printToken("AST", t.image);
        break;
      case MAIS:
        t = jj_consume_token(MAIS);
                printToken("MAIS", t.image);
        break;
      case VIRGULA:
        t = jj_consume_token(VIRGULA);
                   printToken("VIRGULA", t.image);
        break;
      case MENOS_PONTO:
        t = jj_consume_token(MENOS_PONTO);
                       printToken("MENOSPONTO", t.image);
        break;
      case SETAD:
        t = jj_consume_token(SETAD);
                 printToken("SETAD", t.image);
        break;
      case PONTOPONTO:
        t = jj_consume_token(PONTOPONTO);
                      printToken("PONTOPONTO", t.image);
        break;
      case PONTOTIL:
        t = jj_consume_token(PONTOTIL);
                    printToken("PONTOTIL", t.image);
        break;
      case DOISPONTO:
        t = jj_consume_token(DOISPONTO);
                     printToken("DOISPONTO", t.image);
        break;
      case DOISDOISPONTO:
        t = jj_consume_token(DOISDOISPONTO);
                         printToken("DOISDOISPONTO", t.image);
        break;
      case DOISPONTOIGUAL:
        t = jj_consume_token(DOISPONTOIGUAL);
                          printToken("DOISPONTOIGUAL", t.image);
        break;
      case DOISPONTOMAIOR:
        t = jj_consume_token(DOISPONTOMAIOR);
                          printToken("DOISPONTOMAIOR", t.image);
        break;
      case PONTOVIRGULA:
        t = jj_consume_token(PONTOVIRGULA);
                        printToken("PONTOVIRGULA", t.image);
        break;
      case MENOR:
        t = jj_consume_token(MENOR);
                 printToken("MENOR", t.image);
        break;
      case SETAE:
        t = jj_consume_token(SETAE);
                 printToken("SETAE", t.image);
        break;
      case IGUAL:
        t = jj_consume_token(IGUAL);
                 printToken("IGUAL", t.image);
        break;
      case MAIOR:
        t = jj_consume_token(MAIOR);
                 printToken("MAIOR", t.image);
        break;
      case MAIORCH:
        t = jj_consume_token(MAIORCH);
                   printToken("MAIORCH", t.image);
        break;
      case INTER:
        t = jj_consume_token(INTER);
                 printToken("INTER", t.image);
        break;
      case ECOL:
        t = jj_consume_token(ECOL);
                printToken("ECOL", t.image);
        break;
      case MENORCOL:
        t = jj_consume_token(MENORCOL);
                    printToken("MENORCOL", t.image);
        break;
      case MAIORCOLD:
        t = jj_consume_token(MAIORCOLD);
                      printToken("MAIORCOLD", t.image);
        break;
      case DCOL:
        t = jj_consume_token(DCOL);
                printToken("DCOL", t.image);
        break;
      case UNDELINE:
        t = jj_consume_token(UNDELINE);
                    printToken("UNDERLINE", t.image);
        break;
      case CRASE:
        t = jj_consume_token(CRASE);
                 printToken("CRASE", t.image);
        break;
      case ECHAVE:
        t = jj_consume_token(ECHAVE);
                  printToken("ECHAVE", t.image);
        break;
      case ECHAVEMENOR:
        t = jj_consume_token(ECHAVEMENOR);
                       printToken("ECHAVEMENOR", t.image);
        break;
      case OUBIT:
        t = jj_consume_token(OUBIT);
                 printToken("OUBIT", t.image);
        break;
      case OUCOL:
        t = jj_consume_token(OUCOL);
                 printToken("OUCOL", t.image);
        break;
      case OULOG:
        t = jj_consume_token(OULOG);
                 printToken("OULOG", t.image);
        break;
      case DCHAVE:
        t = jj_consume_token(DCHAVE);
                   printToken("DCHAVE", t.image);
        break;
      case TIL:
        t = jj_consume_token(TIL);
               printToken("TIL", t.image);
        break;
      case MENOS:
        t = jj_consume_token(MENOS);
                 printToken("MENOS", t.image);
        break;
      case DOISPONTOVIRGULA:
        t = jj_consume_token(DOISPONTOVIRGULA);
                            printToken("DOISPONTOVIRGULA", t.image);
        break;
      case COLOU:
        t = jj_consume_token(COLOU);
                  printToken("COLOU", t.image);
        break;
      case LINENUM_DIRECTIVE:
        t = jj_consume_token(LINENUM_DIRECTIVE);
                              printToken("LINENUM_DIRECTIVE", t.image);
        break;
      case MAIORIGUAL:
        t = jj_consume_token(MAIORIGUAL);
                      printToken("MAIORIGUAL", t.image);
        break;
      case MENORIGUAL:
        t = jj_consume_token(MENORIGUAL);
                      printToken("MENORIGUAL", t.image);
        break;
      case IGUALIGUAL:
        t = jj_consume_token(IGUALIGUAL);
                      printToken("IGUALIGUAL", t.image);
        break;
      case ASTAST:
        t = jj_consume_token(ASTAST);
                  printToken("ASTAST", t.image);
        break;
      case BARRAPONTO:
        t = jj_consume_token(BARRAPONTO);
                      printToken("BARRAPONTO", t.image);
        break;
      case ASTPONTO:
        t = jj_consume_token(ASTPONTO);
                    printToken("ASTPONTO", t.image);
        break;
      case TILMENOSPONTO:
        t = jj_consume_token(TILMENOSPONTO);
                         printToken("TILMENOSPONTO", t.image);
        break;
      case MAISPONTO:
        t = jj_consume_token(MAISPONTO);
                     printToken("MAISPONTO", t.image);
        break;
      case BARRA:
        t = jj_consume_token(BARRA);
                 printToken("BARRA", t.image);
        break;
      case TILMENOS:
        t = jj_consume_token(TILMENOS);
                    printToken("TILMENOS", t.image);
        break;
      case ARROBA:
        t = jj_consume_token(ARROBA);
                  printToken("ARROBA", t.image);
        break;
      case CHAPEU:
        t = jj_consume_token(CHAPEU);
                  printToken("CHAPEU", t.image);
        break;
      case PONTO:
        t = jj_consume_token(PONTO);
                 printToken("PONTO", t.image);
        break;
      case PREFIX_SYMBOL:
        t = jj_consume_token(PREFIX_SYMBOL);
                         printToken("PREFIX_SYMBOL", t.image);
        break;
      case INFIX_SYMBOL:
        t = jj_consume_token(INFIX_SYMBOL);
                        printToken("INFIX_SYMBOL", t.image);
        break;
      case ID:
        t = jj_consume_token(ID);
              printToken("ID", t.image);
        break;
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
      case FLOAT:
      case CHAR:
      case STRING:
      case LABEL:
      case OPTLABEL:
      case AND:
      case AS:
      case ASSERT:
      case ASR:
      case BEGIN:
      case CONSTRAINT:
      case DO:
      case DONE:
      case DOWNTO:
      case ELSE:
      case EXCEPTION:
      case EXTERNAL:
      case FALSE:
      case FOR:
      case FUN:
      case FUNCTOR:
      case IF:
      case IN:
      case INCLUDE:
      case INHERIT:
      case LAND:
      case LAZY:
      case LET:
      case LOR:
      case LSL:
      case LXOR:
      case MATCH:
      case METHOD:
      case MOD:
      case MODULE:
      case NEW:
      case NONREC:
      case OBJECT:
      case OF:
      case OPEN:
      case PRIVATE:
      case REC:
      case SIG:
      case STRUCT:
      case THEN:
      case TRUE:
      case TRY:
      case TYPE:
      case VAL:
      case VIRTUAL:
      case WHILE:
      case WITH:
      case CLASS:
      case END:
      case FUNCTION:
      case INITIALIZER:
      case LSR:
      case MUTABLE:
      case OR:
      case TO:
      case WHEN:
      case DIFF:
      case HASHTAG:
      case EBIT:
      case ELOG:
      case ASPA:
      case EPAR:
      case DPAR:
      case AST:
      case MAIS:
      case VIRGULA:
      case MENOS_PONTO:
      case SETAD:
      case PONTO:
      case PONTOPONTO:
      case PONTOTIL:
      case DOISPONTO:
      case DOISDOISPONTO:
      case DOISPONTOIGUAL:
      case DOISPONTOMAIOR:
      case PONTOVIRGULA:
      case MENOR:
      case SETAE:
      case IGUAL:
      case MAIORCOLD:
      case MAIORCH:
      case INTER:
      case ECOL:
      case MENORCOL:
      case MAIOR:
      case DCOL:
      case UNDELINE:
      case CRASE:
      case ECHAVE:
      case ECHAVEMENOR:
      case OUBIT:
      case OUCOL:
      case OULOG:
      case DCHAVE:
      case TIL:
      case MENOS:
      case DOISPONTOVIRGULA:
      case COLOU:
      case MAIORIGUAL:
      case MENORIGUAL:
      case IGUALIGUAL:
      case ASTAST:
      case BARRAPONTO:
      case ASTPONTO:
      case TILMENOSPONTO:
      case MAISPONTO:
      case BARRA:
      case TILMENOS:
      case ARROBA:
      case CHAPEU:
      case LINENUM_DIRECTIVE:
      case ID:
      case PREFIX_SYMBOL:
      case INFIX_SYMBOL:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
    }
    jj_consume_token(0);
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public OcamlParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[2];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static private int[] jj_la1_4;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
      jj_la1_init_3();
      jj_la1_init_4();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xffd40200,0xffd40200,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0xffffffff,0xffffffff,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0xffffffff,0xffffffff,};
   }
   private static void jj_la1_init_3() {
      jj_la1_3 = new int[] {0xffffffff,0xffffffff,};
   }
   private static void jj_la1_init_4() {
      jj_la1_4 = new int[] {0x181ff,0x181ff,};
   }

  /** Constructor with InputStream. */
  public OcamlParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public OcamlParser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new OcamlParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public OcamlParser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new OcamlParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public OcamlParser(OcamlParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(OcamlParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List jj_expentries = new java.util.ArrayList();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[145];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 2; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
          if ((jj_la1_3[i] & (1<<j)) != 0) {
            la1tokens[96+j] = true;
          }
          if ((jj_la1_4[i] & (1<<j)) != 0) {
            la1tokens[128+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 145; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
